version: "3"

services:
  client:
    build: client
    image: "client:latest"
    depends_on:
      - gateway
  gateway:
    build: gateway
    ports:
      - "8080:8080"
  session:
    build: session
    depends_on:
      - mongo
      - activemq
  session-test-client:
    build: session-test-client
    depends_on:
      - mongo
      - activemq
      - session
  activemq:
    image: rmohr/activemq:latest
    container_name: activemq
    ports:
      - "8161:8161"
      - "61616:61616"
  mongo:
    image: mongo:4.0.4