version: "3"

services:
#  client:
#    build: client
#    depends_on:
#      - gateway
  gateway:
    build: gateway
    ports:
      - "8080:8080"
    depends_on:
      - load-balancer
  load-balancer:
    build: load-balancer
    ports:
      - "8081:8081"
    depends_on:
      - session
  session:
    build: session
    depends_on:
      - mongo
      - activemq
  activemq:
    image: rmohr/activemq:latest
    container_name: activemq
    ports:
      - "8161:8161"
      - "61616:61616"
  mongo:
    image: mongo:4.0.4
#  session-test-client:
#    build: session-test-client
#    depends_on:
#      - mongo
#      - activemq
#      - session